name: DiffuseMix
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - abseil-cpp=20211102.0=h27087fc_1
  - absl-py=1.4.0=pyhd8ed1ab_0
  - aiohttp=3.8.5=py39h5eee18b_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=openblas
  - blinker=1.6.2=pyhd8ed1ab_0
  - brotlipy=0.7.0=py39hb9d737c_1004
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2023.08.22=h06a4308_0
  - cachetools=5.3.1=pyhd8ed1ab_0
  - certifi=2023.7.22=py39h06a4308_0
  - cffi=1.15.0=py39h4bc2ebd_0
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cryptography=3.4.8=py39h95dcef6_1
  - debugpy=1.6.7=py39h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py39h06a4308_0
  - frozenlist=1.3.3=py39h5eee18b_0
  - google-auth=2.23.0=pyh1a96a4e_0
  - google-auth-oauthlib=1.0.0=pyhd8ed1ab_1
  - grpc-cpp=1.48.2=h5bf31a4_0
  - grpcio=1.48.2=py39h5bf31a4_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - ipykernel=6.25.0=py39h2f386ee_0
  - ipython=8.15.0=py39h06a4308_0
  - joblib=1.2.0=py39h06a4308_0
  - jupyter_client=7.4.9=py39h06a4308_0
  - jupyter_core=5.5.0=py39h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libblas=3.9.0=15_linux64_openblas
  - libcblas=3.9.0=15_linux64_openblas
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libgomp=11.2.0=h1234567_1
  - liblapack=3.9.0=15_linux64_openblas
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - markdown=3.4.4=pyhd8ed1ab_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - multidict=6.0.2=py39h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py39h06a4308_0
  - numpy-base=1.24.3=py39h1e6e340_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openssl=1.1.1w=h7f8727e_0
  - packaging=23.1=py39h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - platformdirs=3.10.0=py39h06a4308_0
  - protobuf=3.20.3=py39h6a678d5_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.16=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyzmq=25.1.0=py39h6a678d5_0
  - re2=2022.04.01=h27087fc_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - setuptools=67.8.0=py39h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tensorboard=2.14.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py39h52d8a92_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.3.3=py39h5eee18b_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - werkzeug=2.1.2=pyhd8ed1ab_1
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yarl=1.7.2=py39hb9d737c_2
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - accelerate==0.24.1
    - annotated-types==0.6.0
    - appdirs==1.4.4
    - asttokens==2.3.0
    - beautifulsoup4==4.12.2
    - blis==0.7.11
    - catalogue==2.0.10
    - clip
    - clip-text-decoder==1.4.4
    - cloudpathlib==0.16.0
    - cmake==3.27.2
    - color-matcher==0.5.0
    - comm==0.1.4
    - confection==0.1.4
    - confusion-matrix==0.1
    - contourpy==1.0.7
    - cycler==0.11.0
    - cymem==2.0.8
    - datasets==2.15.0
    - ddt==1.6.0
    - diffusers==0.24.0
    - dill==0.3.7
    - docker-pycreds==0.4.0
    - docutils==0.20.1
    - et-xmlfile==1.1.0
    - evaluate==0.4.1
    - exceptiongroup==1.1.3
    - executing==1.2.0
    - filelock==3.12.3
    - fonttools==4.39.4
    - fsspec==2023.9.0
    - ftfy==6.1.1
    - gdown==4.7.1
    - gitdb==4.0.10
    - gitpython==3.1.36
    - h5py==3.10.0
    - huggingface-hub==0.19.4
    - imageio==2.30.0
    - importlib-resources==5.12.0
    - ipywidgets==8.1.0
    - jedi==0.19.0
    - jinja2==3.1.2
    - jupyterlab-widgets==3.0.8
    - kiwisolver==1.4.4
    - kornia==0.6.8
    - langcodes==3.3.0
    - lightning-utilities==0.10.0
    - lit==16.0.6
    - lpips==0.1.4
    - markupsafe==2.1.3
    - matplotlib==3.8.0
    - mpmath==1.3.0
    - multiprocess==0.70.15
    - murmurhash==1.0.10
    - networkx==3.1
    - nose==1.3.7
    - numpy==1.26.0
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.3.4.1
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.3.107
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.3.101
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==8.9.7.29
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - nvidia-pyindex==1.0.9
    - nvidia-tensorrt==99.0.0
    - opencv-python==4.7.0.72
    - openpyxl==3.1.2
    - pandas==2.1.1
    - pathtools==0.1.2
    - pillow==9.5.0
    - pip==24.0
    - preshed==3.0.9
    - prompt-toolkit==3.0.39
    - promptcap==1.0.3
    - psutil==5.9.5
    - pyarrow==14.0.1
    - pyarrow-hotfix==0.6
    - pydantic==2.5.2
    - pydantic-core==2.14.5
    - pygments==2.16.1
    - pyparsing==3.0.9
    - pytorch-lightning==2.1.2
    - pytz==2023.3.post1
    - pyyaml==6.0
    - regex==2023.5.5
    - responses==0.18.0
    - safetensors==0.3.3
    - scikit-learn==1.3.2
    - scipy==1.11.3
    - seaborn==0.13.0
    - sentry-sdk==1.31.0
    - setproctitle==1.3.2
    - smart-open==6.4.0
    - smmap==5.0.1
    - soupsieve==2.5
    - spacy==3.7.2
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - srsly==2.4.8
    - stack-data==0.6.2
    - super-image==0.1.7
    - sympy==1.12
    - tensorrt==8.6.1.post1
    - tensorrt-bindings==8.6.1
    - thinc==8.2.1
    - threadpoolctl==3.2.0
    - tokenizers==0.15.0
    - torch==2.0.1
    - torchdata==0.7.1
    - torchmetrics==1.2.1
    - torchsummary==1.5.1
    - torchvision==0.15.2
    - tqdm==4.65.0
    - traitlets==5.9.0
    - transformers==4.35.2
    - triton==2.0.0
    - typer==0.9.0
    - tzdata==2023.3
    - urllib3==2.0.4
    - wandb==0.16.2
    - wasabi==1.1.2
    - wcwidth==0.2.6
    - weasel==0.3.4
    - wget==3.2
    - widgetsnbextension==4.0.8
    - xxhash==3.4.1
    - zipp==3.15.0
prefix: /home/cvpr/anaconda3/envs/DiffuseMix
